%{
[Function Description]
This function extends MATLAB's dir function by filtering out system files and directories.
It removes entries like '.', '..', '.DS_Store', and files starting with '._' that are
automatically generated by macOS, providing a cleaner directory listing.

[Input Arguments]
folder_path: [char] Path to the directory to list (same as dir function input)
additional_name_list: [cell array] (Optional) Additional file names to exclude from results

[Output Arguments]
dir_list: [struct] Filtered directory listing structure (same format as dir function output)
%}

function [dir_list] = dirPlus(folder_path, additional_name_list)
    % Define default files to exclude (current and parent directories)
    excluded_name_list = {'.', '..'};
    
    % Add user-specified exclusions if provided
    if nargin == 2
        excluded_name_list = horzcat(excluded_name_list, additional_name_list);
    end
    
    % Get directory listing
    dir_list = dir(folder_path);
    
    % Remove specified files from the listing
    dir_list = dir_list(~ismember({dir_list.name}, excluded_name_list));

    % Also exclude hidden files and macOS-specific files
    dir_list = dir_list(~startsWith({dir_list.name}, {'.', '._'}));
end

